version: '3.7'
services:
  cron:
    image: afandy/magento2-cron:latest
    build:
      context: ./magento2-cron
      dockerfile: Dockerfile
    depends_on:
      - apache
      - varnish
    links:
      - db
      - cache
      - sessions
      - clusterdata
      - apache
      - varnish
    volumes:
      - type: bind
        source: ./magento2
        target: /var/www/html
        consistency: delegated
      - type: bind
        source: ./varnish.secret
        target: /varnish.secret
        consistency: consistent
      # Enable the next line if you want to add a custom php.ini
      #- ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  ssl:
    image: afandy/magento2-nginx-ssl:latest
    build:
      context: ./magento2-nginx-ssl
      dockerfile: Dockerfile
    depends_on:
      - varnish
    links:
      - varnish
    ports:
      - "443:443"

  varnish:
    image: afandy/magento2-varnish:latest
    build:
      context: ./magento2-varnish
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "6082:6082"
    depends_on:
      - apache
    links:
      - apache
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl
      - ./varnish.secret:/etc/varnish/secret
    environment:
      - CACHE_SIZE=256M

  apache:
    image: afandy/magento2-apache:latest
    build:
      context: ./magento2-apache
      dockerfile: Dockerfile
    depends_on:
      - db
      - cache
      - clusterdata
    links:
      - db
      - cache
      - sessions
      - clusterdata
    volumes:
      - type: bind
        source: ./magento2
        target: /var/www/html
        consistency: delegated
      - ~/.composer/auth.json:/root/.composer/auth.json
      # Enable the next line if you want to add a custom php.ini
      #- ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
        consistency: delegated
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

  cache:
    image: afandy/redis-volatile:latest
    build:
      context: ./redis-volatile
      dockerfile: Dockerfile

  clusterdata:
    image: afandy/redis-volatile:latest

  sessions:
    image: redis

volumes:
  dbdata:
